name: CHECK_PACKAGE_VERSION

on:
  pull_request:
    branches: [ master ]
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: npm install -g yarn
      - name: Get local package version
        run: echo "::set-output name=CURRENT_PACKAGE_VERISION::$(node -p 'require(`./package.json`).version')"
        id: current-package-version
      - name: Get remote package version
        run: echo "::set-output name=REMOTE_PACKAGE_VERISION::$(npm view @1inch/solidity-utils version)"
        id: remote-package-version
      - name: Check Version
        run: echo "Validating ${{ steps.current-package-version.outputs.CURRENT_PACKAGE_VERISION }} against ${{ steps.remote-package-version.outputs.REMOTE_PACKAGE_VERISION }}"
